@startuml   kuis

class Trainner{
    +fullName
}

class Jadwal{
    +waktu
}
'  kdakgsdg
Trainner --|> Jadwal

class Siswa{
    NamaSiswa
    kota
    pendTerakhir
    ipk
    tipe
    jenisBootcamp
    batch
    tahun
}

class Beasiswa extends Siswa{
    insentif
}

class Reguler extends Siswa{
    netPrice
}

class Main{
    +main():function
}

interface APIStudent{
    +totalSiswa():int
    +totalBea():int
    +totalReg():int
    +totalIns():int
    +totalNet():int
}

Main -left-> APIStudent
APIStudent -left-> Siswa
APIStudent --> Beasiswa
APIStudent --> Reguler

@enduml